story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story5.urls')),
]

story5/urls.py
from django.urls import path
from . import views

app_name = 'story5'

urlpatterns = [
    path('', views.index, name='index'),
    path('add-matkul/', views.addmatkul, name='add-matkul'),
    path("delete-matkul/<int:id>",views.delete_matkul,name="delete-matkul"),
    path("/<int:id>",views.detail_matkul,name="detail-matkul")
]

story5/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.
semester_choices = [
    ("2020/2021 Gasal","2020/2021 Gasal"),
    ("2020/2021 Genap","2020/2021 Genap"),
    ("2021/2022 Gasal","2021/2022 Gasal"),
    ("2021/2022 Genap","2021/2022 Genap"),
    ("2022/2023 Gasal","2022/2023 Gasal"),
    ("2022/2023 Genap","2022/2023 Genap")
]

class MatKul(models.Model):
    nama = models.TextField(max_length = 50)
    dosen = models.TextField(max_length = 50)
    sks = models.IntegerField()
    deskripsi = models.TextField(max_length = 500, default='')
    semester = models.TextField(choices = semester_choices)
    ruang = models.TextField(max_length = 50)

    def __str__(self):
        return "{} ({})".format(self.nama,self.dosen)
    
    def get_absolute_url(self):
        return reverse("story5:detail-matkul",args=[self.id])

story5/forms.py
from django import forms
from .models import MatKul

class MatKulForm(forms.ModelForm):
    class Meta:
        model = MatKul
        fields = "__all__"

story5/views.py
from django.shortcuts import render, redirect
from .models import MatKul
from .forms import MatKulForm

# Create your views here.
def index(request):
    context = {
        "list_matkul" : MatKul.objects.all(),
        "page" : "index"
    }
    return render(request, 'index.html', context)

def addmatkul(request):
    if request.method == "POST":
        matkul_form = MatKulForm(request.POST)
        if matkul_form.is_valid():
            matkul_form.save()
        return redirect("story5:index")

    return render(request, 'add-matkul.html')

def delete_matkul(request,id):
    if request.method == "POST":
        matkul = MatKul.objects.get(id=id)
        matkul.delete()
    return redirect("story5:index")

def detail_matkul(request, id):
    matkul = MatKul.objects.get(id=id)
    context = {
        "matkul" : matkul,
    }
    return render(request, 'detail-matkul.html', context)

story5/templates/add-matkul.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="container-fluid form">
    <form method="POST" action="{% url 'story5:add-matkul' %}">
        {% csrf_token %}
        <div class="form-group">
          <label for="exampleFormControlInput1" class="label">Nama Matkul</label>
          <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="Nama Matkul" name="nama" required>
        </div>
        <div class="form-group">
            <label for="exampleFormControlInput1" class="label">Dosen Pengajar</label>
            <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="Nama Dosen Pengajar" name="dosen" required>
        </div>
        <div class="form-group">
            <label for="exampleFormControlInput1" class="label">Ruang Kelas</label>
            <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="Ruang Kelas" name="ruang" required>
        </div>
        <label for="exampleFormControlInput1" class="label">Semester</label>
        <select class="form-control mb-1" name="semester" required>
            <option value="2020/2021 Gasal">2020/2021 Gasal</option>
            <option value="2020/2021 Genap">2020/2021 Genap</option>
            <option value="2021/2022 Gasal">2021/2022 Gasal</option>
            <option value="2021/2022 Genap">2021/2022 Genap</option>
            <option value="2022/2023 Gasal">2022/2023 Gasal</option>
            <option value="2022/2023 Genap">2022/2023 Genap</option>
        </select>
        <label for="exampleFormControlInput1" class="label">Jumlah SKS</label>
        <input class="form-control mr-1 sks-input" type="number" value=1 name="sks" required>
        <label for="exampleFormControlInput1" class="label">Deskripsi Matkul</label>
        <textarea class="form-control w-100 form-transparent description-input" placeholder="Deskripsi Matkul" name="deskripsi" required></textarea>
        <button class="btn btn-primary addbtn" type="submit">Tambah Matkul</button>
    </form>
</div>
{% endblock %}

story5/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />

    <title>Matkul Keeper</title>
    <link rel="stylesheet" href="{% static 'style.css' %}" />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-primary bg-warning fixed-top">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/"
              >Home <span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/add-matkul">Tambah Matkul</a>
          </li>
          <li class="nav-item"></li>
        </ul>
      </div>
    </nav>

    {% block content %} {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

story5/templates/detail-matkul.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="the-matkul p-3 row rounded-lg mb-3">
    <div class="col-3"></div>
    <div class="col-4 matkul-container">
        <h2 class="p-0 m-0 matkul-name detail">
            {{matkul.nama}}
        </h2>
        <p class="p-0 m-0 matkul-ruang detail">Ruangan: {{matkul.ruang}}</p>
        <p class="p-0 m-0 matkul-dosen detail">Dosen Pengajar: {{matkul.dosen}}</p>
    </div>
    <div class="col-3 sksem">
        <p class="p-0 m-0 matkul-sks detail">Jumlah SKS: {{matkul.sks}} SKS</p>
        <p class="p-0 m-0 matkul-dosen detail">Semester: {{matkul.semester}}</p>
    </div>
    <div class="col-2"></div>
    <div class="col-3"></div>
    <div class="col-7 desktail">
        <p class="p-0 m-0 matkul-sks detail">Deskripsi Matkul:</p>
        <div class="desc p-2 mt-2 rounded-lg desk">
            {{matkul.deskripsi}}
        </div>
    </div>
    <div class="col-2"></div>
</div>
{% endblock %}

story5/templates/index.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="container-fluid matkuls">
    {% for matkul in list_matkul %}
        <div class="matkul-list p-3 row rounded-lg mb-3">
            <div class="col-3"></div>
            <div class="col-4 matkul-container">
                <h2 class="p-0 m-0 matkul-name">
                    <a class="matkul-name" href={{matkul.get_absolute_url}}>
                        {{matkul.nama}}
                    </a>
                </h2>
                <p class="p-0 m-0 matkul-ruang">Ruangan: {{matkul.ruang}}</p>
                <p class="p-0 m-0 matkul-dosen">Dosen Pengajar: {{matkul.dosen}}</p>
                <p class="p-0 m-0 matkul-dosen">Jumlah SKS: {{matkul.sks}}</p>
            </div>
            <div class="col-3 delbtn">
                <form action="{% url 'story5:delete-matkul' matkul.id %}" method="POST">
                    {% csrf_token %}
                    <button class="btn btn-danger btn-lg" type="input">
                        Hapus Matkul
                    </button>
                </form>
            </div>
            <div class="col-2"></div>
        </div>
        {% endfor %}
</div>
{% endblock %}